trigger:
- main

resources:
- repo: self

parameters:
- name: tag
  default: '$(Build.BuildId)'

- name: imageName
  default: 'test-page'

stages:
- stage: CI
  displayName: CI Workflow

  jobs:
  - job: Build
    displayName: Build
    pool: local-agent

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: ${{ parameters.imageName }}
        command: build
        dockerfile: '**/Dockerfile'
        tags: ${{ parameters.tag }}
        containerRegistry: registryConnectionTestPage

    - task: Docker@2
      displayName: Push to ACR
      inputs:
        command: push
        containerRegistry: registryConnectionTestPage
        repository: ${{ parameters.imageName }}
        tags: ${{ parameters.tag }}